// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmbrhqqesjxhhzykvqim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtYnJocXFlc2p4aGh6eWt2cWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDQ4NTksImV4cCI6MjA2NDc4MDg1OX0.TE9AFDv0Gk4dd8TI3fGIMvm2oj4qNBJPmPakb_1HIIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);